# Generated by Django 2.1.2 on 2018-10-15 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='link_video',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='watch.Video'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='link_watch',
            field=models.ManyToManyField(related_name='video', to='watch.Category', verbose_name='Категория'),
        ),
    ]
