# Generated by Django 2.1.2 on 2018-10-15 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0002_auto_20181015_0414'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='video',
            name='link_video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watch.Link'),
        ),
    ]
