# Generated by Django 2.1.2 on 2018-10-15 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0003_auto_20181015_0419'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['title'], 'verbose_name': 'Ссылка', 'verbose_name_plural': 'Ссылки'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Видео', 'verbose_name_plural': 'Видео'},
        ),
        migrations.AddField(
            model_name='video',
            name='description_watch',
            field=models.TextField(blank=True, db_index=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='video',
            name='link_video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_video', to='watch.Link'),
        ),
    ]
